---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/squid
    tags: [latest]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: livingdocs/squid
    tags: [latest, 5.1]

  when:
    branch: [master]

trigger:
  event: [push]

---
kind: signature
hmac: 519011b7856b47db0ec5a885825fff5101047b09cc50f30b10aed9af47f1d70c

...
